export const evals = [
  {
    id: 3,
    name: 'Geography Knowledge',
  },
  {
    id: 4,
    name: 'Math Problem Solving',
  },
  {
    id: 5,
    name: 'General Knowledge',
  },
];

export const evalResults = [
  {
    id: 5,
    evalId: 3,
    input: 'What is the capital of Japan?',
    output: 'Tokyo',
    passed: false,
  },
  {
    id: 6,
    evalId: 3,
    input: 'What is the largest country by land area?',
    output: 'Russia',
    passed: true,
  },
  {
    id: 7,
    evalId: 3,
    input: 'Which continent is Egypt located in?',
    output: 'Africa',
    passed: true,
  },
  {
    id: 8,
    evalId: 3,
    input: 'What is the capital of Australia?',
    output: 'Sydney',
    passed: false,
  },
  {
    id: 9,
    evalId: 3,
    input: 'Which country is known as the Land of the Rising Sun?',
    output: 'Japan',
    passed: true,
  },
  {
    id: 10,
    evalId: 3,
    input: 'What is the smallest country in the world?',
    output: 'Vatican City',
    passed: true,
  },
  {
    id: 11,
    evalId: 3,
    input: 'Which mountain range separates Europe from Asia?',
    output: 'The Ural Mountains',
    passed: true,
  },
  {
    id: 12,
    evalId: 3,
    input: 'What is the capital of Brazil?',
    output: 'Rio de Janeiro',
    passed: false,
  },
  {
    id: 13,
    evalId: 3,
    input: 'Which country is home to the Great Barrier Reef?',
    output: 'Australia',
    passed: true,
  },
  {
    id: 14,
    evalId: 3,
    input: 'What is the largest desert in the world?',
    output: 'Sahara Desert',
    passed: false,
  },
  {
    id: 15,
    evalId: 3,
    input: 'Which river is the longest in the world?',
    output: 'Nile River',
    passed: true,
  },
  {
    id: 16,
    evalId: 3,
    input: 'What is the capital of Canada?',
    output: 'Toronto',
    passed: false,
  },
  {
    id: 17,
    evalId: 3,
    input: 'Which country is known for the Taj Mahal?',
    output: 'India',
    passed: true,
  },
  {
    id: 18,
    evalId: 3,
    input: 'What is the capital of Argentina?',
    output: 'Buenos Aires',
    passed: true,
  },
  {
    id: 19,
    evalId: 3,
    input: 'Which ocean is the largest?',
    output: 'Pacific Ocean',
    passed: true,
  },
  {
    id: 20,
    evalId: 3,
    input: 'What is the capital of South Korea?',
    output: 'Seoul',
    passed: true,
  },
  {
    id: 21,
    evalId: 3,
    input: 'Which country is known as the Land of Fire and Ice?',
    output: 'Iceland',
    passed: true,
  },
  {
    id: 22,
    evalId: 3,
    input: 'What is the capital of Italy?',
    output: 'Rome',
    passed: true,
  },
  {
    id: 23,
    evalId: 3,
    input: 'Which country has the most people?',
    output: 'India',
    passed: false,
  },
  {
    id: 24,
    evalId: 3,
    input: 'What is the highest mountain in the world?',
    output: 'Mount Everest',
    passed: true,
  },
  {
    id: 25,
    evalId: 4,
    input: 'What is 7 + 8?',
    output: '15',
    passed: true,
  },
  {
    id: 26,
    evalId: 4,
    input: 'What is 12 × 12?',
    output: '144',
    passed: false,
  },
  {
    id: 27,
    evalId: 4,
    input: 'What is the square root of 64?',
    output: '8',
    passed: true,
  },
  {
    id: 28,
    evalId: 4,
    input: 'What is 15% of 200?',
    output: '30',
    passed: true,
  },
  {
    id: 29,
    evalId: 4,
    input: 'If x + 5 = 12, what is x?',
    output: '7',
    passed: true,
  },
  {
    id: 30,
    evalId: 4,
    input: 'What is 3² + 4²?',
    output: '25',
    passed: true,
  },
  {
    id: 31,
    evalId: 4,
    input: 'What is the area of a circle with radius 5?',
    output: '78.5',
    passed: false,
  },
  {
    id: 32,
    evalId: 4,
    input: 'What is 17 - 9?',
    output: '8',
    passed: true,
  },
  {
    id: 33,
    evalId: 4,
    input: 'What is 24 ÷ 6?',
    output: '4',
    passed: true,
  },
  {
    id: 34,
    evalId: 4,
    input: 'What is the next number in the sequence: 2, 4, 8, 16, ...?',
    output: '32',
    passed: true,
  },
  {
    id: 35,
    evalId: 4,
    input: 'What is the value of π (pi) to 2 decimal places?',
    output: '3.14',
    passed: true,
  },
  {
    id: 36,
    evalId: 4,
    input: 'What is the perimeter of a square with sides of length 7?',
    output: '28',
    passed: true,
  },
  {
    id: 37,
    evalId: 4,
    input: 'What is 5! (5 factorial)?',
    output: '120',
    passed: true,
  },
  {
    id: 38,
    evalId: 4,
    input: 'Solve for x: 2x - 7 = 15',
    output: '11',
    passed: true,
  },
  {
    id: 39,
    evalId: 4,
    input: 'What is the sum of angles in a triangle?',
    output: '180 degrees',
    passed: true,
  },
  {
    id: 40,
    evalId: 4,
    input: 'What is 0.25 as a fraction in lowest terms?',
    output: '1/4',
    passed: true,
  },
  {
    id: 41,
    evalId: 4,
    input: 'What is the value of log₁₀(100)?',
    output: '2',
    passed: true,
  },
  {
    id: 42,
    evalId: 4,
    input: 'What is the area of a rectangle with length 8 and width 5?',
    output: '40',
    passed: true,
  },
  {
    id: 43,
    evalId: 4,
    input: 'What is 2³ × 2²?',
    output: '32',
    passed: true,
  },
  {
    id: 44,
    evalId: 4,
    input: 'What is the Pythagorean theorem?',
    output: 'a² + b² = c²',
    passed: false,
  },
  {
    id: 45,
    evalId: 5,
    input: "Who wrote 'Romeo and Juliet'?",
    output: 'William Shakespeare',
    passed: false,
  },
  {
    id: 46,
    evalId: 5,
    input: 'What is the chemical symbol for gold?',
    output: 'Au',
    passed: true,
  },
  {
    id: 47,
    evalId: 5,
    input: 'Who painted the Mona Lisa?',
    output: 'Leonardo da Vinci',
    passed: true,
  },
  {
    id: 48,
    evalId: 5,
    input: 'What is the largest organ in the human body?',
    output: 'Skin',
    passed: true,
  },
  {
    id: 49,
    evalId: 5,
    input: 'In which year did World War II end?',
    output: '1945',
    passed: false,
  },
  {
    id: 50,
    evalId: 5,
    input: 'What is the main ingredient in guacamole?',
    output: 'Avocado',
    passed: false,
  },
  {
    id: 51,
    evalId: 5,
    input: 'Who was the first person to walk on the moon?',
    output: 'Neil Armstrong',
    passed: true,
  },
  {
    id: 52,
    evalId: 5,
    input: 'What is the capital of Spain?',
    output: 'Madrid',
    passed: true,
  },
  {
    id: 53,
    evalId: 5,
    input: 'Which planet is known as the Red Planet?',
    output: 'Mars',
    passed: true,
  },
  {
    id: 54,
    evalId: 5,
    input: 'What is the chemical formula for water?',
    output: 'H2O',
    passed: true,
  },
  {
    id: 55,
    evalId: 5,
    input: "Who is the author of 'Harry Potter'?",
    output: 'J.K. Rowling',
    passed: true,
  },
  {
    id: 56,
    evalId: 5,
    input: 'What is the tallest mammal?',
    output: 'Giraffe',
    passed: true,
  },
  {
    id: 57,
    evalId: 5,
    input: 'What is the hardest natural substance on Earth?',
    output: 'Diamond',
    passed: true,
  },
  {
    id: 58,
    evalId: 5,
    input: 'Who invented the telephone?',
    output: 'Thomas Edison',
    passed: false,
  },
  {
    id: 59,
    evalId: 5,
    input: 'What is the largest species of shark?',
    output: 'Whale shark',
    passed: true,
  },
  {
    id: 60,
    evalId: 5,
    input: "Which element has the chemical symbol 'O'?",
    output: 'Oxygen',
    passed: true,
  },
  {
    id: 61,
    evalId: 5,
    input: "Who painted 'Starry Night'?",
    output: 'Vincent van Gogh',
    passed: true,
  },
  {
    id: 62,
    evalId: 5,
    input: 'What is the national animal of Australia?',
    output: 'Kangaroo',
    passed: true,
  },
  {
    id: 63,
    evalId: 5,
    input: 'What is the smallest prime number?',
    output: '1',
    passed: false,
  },
  {
    id: 64,
    evalId: 5,
    input: "Who wrote 'The Origin of Species'?",
    output: 'Charles Darwin',
    passed: true,
  },
];
